# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ethan Cho
tagline:          'A Jekyll theme'
description:      'Software Engineer from Vancouver, Canada. Attentive to detail and strives to write clean, efficient code.'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

site:           http://ethanswcho.github.io
github:         https://github.com/poole/hyde
linkedin:       https://www.linkedin.com/in/ethanswcho

blackjack:      https://github.com/ethanswcho/BlackJack
kanjitester:    https://github.com/ethanswcho/KanjiTester
stockalert:     https://github.com/ethanswcho/StockAlert
